version: '3.0'

services:
    faucet-frontend:
        image: "abiosoft/caddy:1.0.0-php-no-stats"
        restart: always
        container_name: faucet-frontend
        env_file: .env
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
            #- "[::]:80:80"
            #- "[::]:443:443"
        volumes:
            - ./services/caddy/caddyfile:/etc/Caddyfile:ro
            - $FRONTEND_PATH:$FRONTEND_CONT_ENDPOINT:ro
            - ./services/caddy/https-certs:/root/.caddy
        links:
            - faucet-db
        environment:
            - ACME_AGREE=true
        networks:
        - karbo-faucet-network
    
    ## FOR DB DEBUG PURPOSES ONLY!
    #phpmyadmin:
    #    image: phpmyadmin/phpmyadmin
    #    env_file: .env
    #    restart: always
    #    container_name: phpmyadmin
    #    ports:
    #       - 8080:80
    #    networks:
    #        - karbo-faucet-network
    #    environment:
    #    #    - MYSQL_USER=$DB_USER
    #    #    - MYSQL_PASSWORD=$DB_PASS
    #    #    - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASS
    #        - PMA_HOST=faucet-db
    #    links:
    #       - faucet-db
    
    faucet-db:
        image: mariadb
        env_file: .env
        restart: always
        container_name: faucet-db
        expose:
            - "3306"
        networks:
            - karbo-faucet-network
        volumes:
            - ./services/mariadb/init:/docker-entrypoint-initdb.d:ro
            - ./services/mariadb/mysql:/var/lib/mysql:rw
            - ./services/mariadb/logs:/var/log/mysql:rw
        environment:
            - MYSQL_USER=$DB_USER
            - MYSQL_PASSWORD=$DB_PASS
            - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASS

    karbo-node:
        image: "looongcat/karbo-fullnode:$NODE_VERSION"
        restart: always
        env_file: .env
        container_name: karbo-node
        expose:
            - "32347"
            - "32348"
        volumes:
            - "$BLOCKCHAIN_PATH:/home/karbo/.karbowanec"
        command:
            - "--fee-address=$FEE_ADDRESS"
        networks:
            - karbo-faucet-network
    
    karbo-wallet:
        image: "looongcat/karbo-fullnode:$NODE_VERSION"
        restart: always
        env_file: .env
        container_name: karbo-wallet
        volumes:
            - $WALLET_FOLDER_PATH:/home/karbo/wallets
        expose:
            - "8070"
        networks:
            - karbo-faucet-network
        entrypoint:
            - simplewallet
            - --wallet-file=/home/karbo/wallets/$WALLET_FILENAME
            - --pass=$WALLET_PASS
            - --rpc-bind-port=8070
            - --rpc-bind-ip=0.0.0.0
            - --daemon-host=karbo-node
            - --daemon-port=32348
        
networks:
    karbo-faucet-network:
        driver: bridge